spring:
  datasource:
    url: jdbc:mysql://localhost:3309/db_conduit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true #unwrap root value @JsonRootName
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: debug