// Code generated by Kitex v0.0.8. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"user/kitex_gen/user_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *user_service.LoginRequest, callOptions ...callopt.Option) (r *user_service.LoginResponse, err error)
	Register(ctx context.Context, Req *user_service.RegisterRequest, callOptions ...callopt.Option) (r *user_service.RegisterResponse, err error)
	Authenticate(ctx context.Context, Req *user_service.AuthenticateRequest, callOptions ...callopt.Option) (r *user_service.AuthenticateResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *user_service.LoginRequest, callOptions ...callopt.Option) (r *user_service.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *user_service.RegisterRequest, callOptions ...callopt.Option) (r *user_service.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) Authenticate(ctx context.Context, Req *user_service.AuthenticateRequest, callOptions ...callopt.Option) (r *user_service.AuthenticateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Authenticate(ctx, Req)
}
