spring:
  datasource:
    url: jdbc:mysql://localhost:3309/db_conduit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true #unwrap root value @JsonRootName
  jpa:
    show-sql: true
  kafka:
    producer:
      retries: 1
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    org:
      springframework:
        security: info
        cache: info